package de.fiereu.openmmo.common.enums

/**
 * The Expansion's `MOVE_EFFECT_*` vocabulary: what a move does in addition to its main effect,
 * listed on the move as `additionalEffects` (each with a chance and a self flag) or named by an
 * `argument` such as `nonVolatileStatus`. Names are the constants with the prefix dropped.
 */
enum class MoveAdditionalEffect {
  NONE,
  SLEEP,
  POISON,
  BURN,
  FREEZE,
  PARALYSIS,
  TOXIC,
  FROSTBITE,
  CONFUSION,
  FLINCH,
  TRI_ATTACK,
  UPROAR,
  PAYDAY,
  WRAP,
  STAT_PLUS,
  STAT_MINUS,
  REMOVE_ARG_TYPE,
  RECHARGE,
  RAGE,
  PREVENT_ESCAPE,
  NIGHTMARE,
  GLAIVE_RUSH,
  REMOVE_STATUS,
  THRASH,
  CLEAR_SMOG,
  FLAME_BURST,
  FEINT,
  HAPPY_HOUR,
  CORE_ENFORCER,
  THROAT_CHOP,
  INCINERATE,
  BUG_BITE,
  RECOIL_HP_25,
  TRAP_BOTH,
  ROUND,
  DIRE_CLAW,
  SYRUP_BOMB,
  FLORAL_HEALING,
  SECRET_POWER,
  PSYCHIC_NOISE,
  TERA_BLAST,
  ORDER_UP,
  ION_DELUGE,
  HAZE,
  LEECH_SEED,
  REFLECT,
  LIGHT_SCREEN,
  SALT_CURE,
  EERIE_SPELL,
  FLING,
  RAINBOW,
  SEA_OF_FIRE,
  SWAMP,
  SUN,
  RAIN,
  SANDSTORM,
  HAIL,
  MISTY_TERRAIN,
  GRASSY_TERRAIN,
  ELECTRIC_TERRAIN,
  PSYCHIC_TERRAIN,
  VINE_LASH,
  WILDFIRE,
  CANNONADE,
  EFFECT_SPORE_SIDE,
  PARALYZE_SIDE,
  CONFUSE_PAY_DAY_SIDE,
  CRIT_PLUS_SIDE,
  PREVENT_ESCAPE_SIDE,
  AURORA_VEIL,
  INFATUATE_SIDE,
  RECYCLE_BERRIES,
  POISON_SIDE,
  DEFOG,
  POISON_PARALYZE_SIDE,
  HEAL_TEAM,
  SPITE,
  GRAVITY,
  VOLCALITH,
  SANDBLAST_SIDE,
  YAWN_FOE,
  LOWER_EVASIVENESS_SIDE,
  AROMATHERAPY,
  CONFUSE_SIDE,
  STEELSURGE,
  STEALTH_ROCK,
  TORMENT_SIDE,
  FIRE_SPIN_SIDE,
  FIXED_POWER,
  BREAK_SCREEN,
  STEAL_STATS,
  BEAT_UP_MESSAGE,
  ITEM_MESSAGE,
  FREEZE_OR_FROSTBITE,
  /** A constant this build does not know; kept so the table still loads. */
  UNKNOWN;

  companion object {
    fun byConstant(token: String): MoveAdditionalEffect {
      val name = token.removePrefix("MOVE_EFFECT_")
      return entries.firstOrNull { it.name == name } ?: UNKNOWN
    }
  }
}
